name: Deploy to Ubuntu Server

on:
  push:
    branches:
      - release-branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
        
      - name: Install dependencies (root)
        run: npm i --legacy-peer-deps

      - name: Run frontend build script
        env:
          CI: false
          REACT_APP_GOOGLE_MAPS_API_KEY: ${{secrets.REACT_APP_GOOGLE_MAPS_API_KEY}}
          REACT_APP_VAPID_KEY: ${{secrets.REACT_APP_VAPID_KEY}}
          REACT_APP_API_KEY: ${{secrets.REACT_APP_API_KEY}}
          REACT_APP_AUTH_DOMAIN: ${{secrets.REACT_APP_AUTH_DOMAIN}}
          REACT_APP_PROJECT_ID: ${{secrets.REACT_APP_PROJECT_ID}}
          REACT_APP_STORAGE_BUCKET: ${{secrets.REACT_APP_STORAGE_BUCKET}}
          REACT_APP_MESSAGING_SENDER_ID: ${{secrets.REACT_APP_MESSAGING_SENDER_ID}}
          REACT_APP_APP_ID: ${{secrets.REACT_APP_APP_ID}}
          REACT_APP_MEASUREMENT_ID: ${{secrets.REACT_APP_MEASUREMENT_ID}}
        run: |
          cd frontend
          npm cache clean --force
          npm i --force  
          npm run build

      - name: Upload Frontend to Ubuntu server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: ${{ secrets.SERVER_PORT }}
          source: ./frontend/build/
          target: /home/mike/villages-mern-git
      
      - name: Upload Backend to Ubuntu server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: ${{ secrets.SERVER_PORT }}
          source: ./backend/
          target: /home/mike/villages-mern-git/backend
          
      - name: Execute deploy.sh script
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            chmod +x /home/mike/villages-mern-git/backend/deploy.sh
            /home/mike/villages-mern-git/backend/deploy.sh
